on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fibley-c/laravel-cms:main
 
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel-cms
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan migrate:refresh --seed
 
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/